### PR TITLE
add default folder so it can be stored

### PR DESCRIPTION
**Pull request by Hellowlol**
to a persistent storage.

### CODE REVIEW

**Comment by McCloud** [comment]
This likely doesn't need to be exposed to any users, they just need to know where to mount their docker volume for persistent storage.

**Comment by Hellowlol** [comment]
I added this is a could add bw_plex to my unraid system.  I have uploaded my own version to dockerhub, so it doesn’t really matter:)

**Comment by McCloud** [comment]
Yeah, I just manually mapped the volume via unraid for mine.

**Comment by Hellowlol** [comment]
Yeah, you should map access to the tvshows etc like plex, if you do you should be able to create edls and chapters too :)

**Pull request merged**
